In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [5]:
a = np.array([])
print(a, type(a))

[] <class 'numpy.ndarray'>


In [15]:
a = np.array([10,20,30,40, 50])
print(a, type(a))
print(a.dtype)
print(a.size)
print(a.itemsize)
print(a.shape)
print(dir(a))

[10 20 30 40 50] <class 'numpy.ndarray'>
int32
5
4
(5,)
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [17]:
mat = np.array( [[1,2,3], [5,6]] )
print(mat)
print(mat.shape)
print(mat.dtype)

[list([1, 2, 3]) list([5, 6])]
(2,)
object


In [18]:
a = np.array([10.0,20,30,40, 50])
print(a, type(a))
print(a.dtype)
print(a.itemsize)

[10. 20. 30. 40. 50.] <class 'numpy.ndarray'>
float64
8


In [20]:
mat = np.array([ [1,2,3,4], [3,4,5,6], [1,2,3,4]])
print(mat.shape)
print(mat)

(3, 4)
[[1 2 3 4]
 [3 4 5 6]
 [1 2 3 4]]


In [21]:
a = np.array([10.0,20,30,40, 50], dtype = 'float32')
print(a, type(a))
print(a.dtype)
print(a.itemsize)

[10. 20. 30. 40. 50.] <class 'numpy.ndarray'>
float32
4


In [23]:
a = np.array([100000000000,20,30,40, 50], )
print(a, type(a))
print(a.dtype)
print(a.itemsize)

[10000    20    30    40    50] <class 'numpy.ndarray'>
int32
4


In [30]:
a = np.array([10,20,30,128, 50], dtype = 'int8') # -128 - +127
print(a, type(a))
print(a.dtype)
print(a.itemsize)
print(a)

[  10   20   30 -128   50] <class 'numpy.ndarray'>
int8
1
[  10   20   30 -128   50]


In [33]:
a = np.array([10,20,30,256, 50], dtype = 'uint8')
print(a, type(a))
print(a.dtype)
print(a.itemsize)
print(a)

[10 20 30  0 50] <class 'numpy.ndarray'>
uint8
1
[10 20 30  0 50]


In [38]:
a = np.array([10,29], dtype = np.int16)
print(a, a.dtype)
s = a.astype(dtype = 'str')
print(s)
print(s.itemsize)


[10 29] int16
['10' '29']
24


In [40]:
a = np.array([10,29], dtype = 'i8')
print(a, a.dtype)
s = a.astype(dtype = 'str')
print(s)
print(s.itemsize)
print(s.dtype)

[10 29] int64
['10' '29']
84
<U21


In [ ]:
33
32 16 8 4 2 1
0001 0001


456

450

056

In [46]:
a = np.array( [ 1,2,3, 'a', [1,2]] )
print(a)
print(a.dtype)

[1 2 3 'a' list([1, 2])]
object


In [53]:
a = np.arange(1,10)
print(a)
print(a.dtype)
print(type(a))
print(np.arange(10))
print(np.arange(10,20,2))
print(np.arange(10,20,2, dtype = 'f4'))

[1 2 3 4 5 6 7 8 9]
int32
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]
[10. 12. 14. 16. 18.]


In [57]:
z = np.ones(5, dtype = np.int8)
print(z)
z = np.zeros((5,2), dtype = np.int8)
print(z)

[1 1 1 1 1]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [72]:
l = np.arange(1,90,20)
print(l)
l = np.linspace(1,80,40)
print(l)
l = np.linspace(1,10,10)
print(l)
l = np.linspace(1,80,40, dtype = 'int8')
print(l)

l = np.linspace(10,20,10)
print(l)
#(20-10)/(10-1) # AP

[ 1 21 41 61 81]
[ 1.          3.02564103  5.05128205  7.07692308  9.1025641  11.12820513
 13.15384615 15.17948718 17.20512821 19.23076923 21.25641026 23.28205128
 25.30769231 27.33333333 29.35897436 31.38461538 33.41025641 35.43589744
 37.46153846 39.48717949 41.51282051 43.53846154 45.56410256 47.58974359
 49.61538462 51.64102564 53.66666667 55.69230769 57.71794872 59.74358974
 61.76923077 63.79487179 65.82051282 67.84615385 69.87179487 71.8974359
 73.92307692 75.94871795 77.97435897 80.        ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 80]
[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [76]:
print((2.0 - 1.0) == (3.0 - 2.0))

f = np.int64(10)/ np.int64(3)
print(f)

True
3.3333333333333335


In [81]:
print(dir(np.random))
n = np.random.randint(10)
print(n)
n = np.random.randint(10,20)
print(n)
n = np.random.randint(10,20,40)
print(n)
n = np.random.randn(40)
print(n)

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']
8
15
[16 16 12 12 17 18 14 12 10 18 19 11 10 14 14 18 11 19 19 14 12 12 14 13
 18 1

In [87]:
mat1 = np.arange(1,17).reshape(4,4)
print(mat1)
mat2 = np.arange(1,17).reshape(2,8)
print(mat2)
print(mat1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


ValueError: cannot reshape array of size 16 into shape (2,9)

In [96]:
mat1 = np.arange(1,25).reshape(3,2,4)
print(mat1)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [93]:
mat = np.arange(1,17)
mat.resize(2,20)
print(mat)

mat = np.arange(1,17)
mat.resize(2,5)
print(mat)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [108]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)

print()
print(mat1[1])
print()
print(mat1[1,1])
print()
print(mat1[1,2])

print()
print(mat1[1:])
print()
print(mat1[1:3, 3])
print()
print(mat1[1:3, :2])
print(mat1[1:3, [1,3]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 6  7  8  9 10]

7

8

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 9 14]

[[ 6  7]
 [11 12]]
[[ 7  9]
 [12 14]]


In [115]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)

print(mat1[3:1:-1, [1,3]]) # [d0, d1,...]
print(mat1[:,4])           #[s0:e0:step0   ,s1:e1:step1....    ]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[17 19]
 [12 14]]
[ 5 10 15 20]


In [116]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)
print( mat1 + 20 )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [124]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)
mat2 = np.arange(100,120).reshape(4,5)
print(mat2)

mat3 = mat1 + mat2
print(mat3)
mat3 = mat1 * mat2
print(mat3)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]
[[101 103 105 107 109]
 [111 113 115 117 119]
 [121 123 125 127 129]
 [131 133 135 137 139]]
[[ 100  202  306  412  520]
 [ 630  742  856  972 1090]
 [1210 1332 1456 1582 1710]
 [1840 1972 2106 2242 2380]]
<built-in method dot of numpy.ndarray object at 0x0000016B70E0B990>


In [129]:
mat1 = np.arange(1,21).reshape(4,5)
print(mat1)
print(mat1.min())
print(mat1.max())
print(mat1.min(axis = 1))
print(mat1.max(axis = 1))
print(mat1.min(axis = 0))
print(mat1.max(axis = 0))
print()
print(mat1.sum(axis = 1))
print(mat1.sum(axis = 1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
1
20
[ 1  6 11 16]
[ 5 10 15 20]
[1 2 3 4 5]
[16 17 18 19 20]

[15 40 65 90]
[15 40 65 90]


In [139]:
mat = np.random.randint(1,10,12).reshape(3,4)
print(mat)

[[9 9 6 7]
 [7 5 8 6]
 [8 5 6 3]]


In [141]:
r = mat > 5
print(r)
print(mat[r])
print(~r)
print(mat[~r])

r = (mat > 5) & (mat <=7) # & for and;  | for or
print(r)
print(mat[r])

[[ True  True  True  True]
 [ True False  True  True]
 [ True False  True False]]
[9 9 6 7 7 8 6 8 6]
[[False False False False]
 [False  True False False]
 [False  True False  True]]
[5 5 3]
[[False False  True  True]
 [ True False False  True]
 [False False  True False]]
[6 7 7 6 6]


In [153]:
a = np.array( [ 10,20,30, np.nan])
print(a)
print(np.nan == np.nan)
print(np.isnan(a))
print(np.isnan(a).any())
print(np.isnan(a).all())

a%2 == 0


[10. 20. 30. nan]
False
[False False False  True]
True
False


In [154]:
mat = np.random.randint(1,10,12).reshape(3,4)
print(mat)

[[9 9 2 9]
 [7 1 8 5]
 [8 2 1 2]]


In [162]:
r1 = np.where( (mat == 9) | (mat == 8),10,20 )
print(r1)

print(mat)
mat[np.where(mat == 9)] = 100000
print(mat)

[[20 20 20 20]
 [20 20 10 20]
 [10 20 20 20]]
[[100000 100000      2 100000]
 [     7      1      8      5]
 [     8      2      1      2]]
[[100000 100000      2 100000]
 [     7      1      8      5]
 [     8      2      1      2]]


In [165]:
mat = np.random.randint(1,10,12).reshape(3,4)
print(mat)

[[3 1 4 2]
 [4 7 8 7]
 [6 6 6 2]]


In [166]:
print(mat > 5)
print(mat < 8)
print((mat > 5) & (mat < 8))

[[False False False False]
 [False  True  True  True]
 [ True  True  True False]]
[[ True  True  True  True]
 [ True  True False  True]
 [ True  True  True  True]]
[[False False False False]
 [False  True False  True]
 [ True  True  True False]]


In [171]:
mat0 = np.ones(10).reshape(2,5)
print(mat)
mat1 = np.zeros(10).reshape(2,5)

mat2 = np.vstack([mat0 ,mat1])
print(mat2)

mat2 = np.hstack([mat0 ,mat1, mat0])
print(mat2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]]
