In [3]:
t = (1,2,3,4,5)
l = list(t)
print(l)

[1, 2, 3, 4, 5]


In [11]:
L = [1,3,5,7]
T = (8,6,4,2)
LS = L + list(T)
print(LS)

[1, 3, 5, 7, 8, 6, 4, 2]


In [15]:
#Lists and Tuples are sequence data types that can store a collection of items.
#List are Mutable
#Tuples are Immutable

L = [1,3,5,7]
T = (8,6,4,2)

L[2] = 9
print(L)

T[2] = 5

[1, 3, 9, 7]


TypeError: 'tuple' object does not support item assignment

In [14]:
l = ['a','d','c','A','C']
print(l[::-1])

['C', 'A', 'c', 'd', 'a']


In [24]:
l = [10,11,20,21,30,31,40,41]
print(l[1::2])

[11, 21, 31, 41]


In [31]:
#copy list in diff ways

list = ['abc',1,2.3]
new_list = list.copy()
new_list.append('def')
print("old list:",list)
print(new_list)

list.append(30)
print(list)

list.append([1,2])
print(list)

list.extend([1,2])
print(list)

old list: ['abc', 1, 2.3]
['abc', 1, 2.3, 'def']
['abc', 1, 2.3, 30]
['abc', 1, 2.3, 30, [1, 2]]
['abc', 1, 2.3, 30, [1, 2], 1, 2]


In [34]:
n_list = ["Happy",[2,0,1,5]]
print(n_list[0][1])
print(n_list[1][3])

a
5


In [36]:
odd = [2,4,6,8]
odd[0] =1
print(odd)
odd[1:4]=[3,5,7]
print(odd)

[1, 4, 6, 8]
[1, 3, 5, 7]


In [2]:
odd = [1, 3, 5]
odd.append([7, 9])
print(odd)
odd.extend([11,13])
print(odd)

[1, 3, 5, [7, 9]]
[1, 3, 5, [7, 9], 11, 13]


In [3]:
x = 1,2,3; print(type(x))
x = (1); print(type(x))
x = 1; print(type(x))
x = 1,; print(type(x))

<class 'tuple'>
<class 'int'>
<class 'int'>
<class 'tuple'>


In [21]:
list = array([1,2,3,4,5,6,7,8,9])
m = reshape(list,(3,3))
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
t1 = tuple('string')
t3 = t1 + t1
print(t3)

('s', 't', 'r', 'i', 'n', 'g', 's', 't', 'r', 'i', 'n', 'g')


In [25]:
t1 = tuple('string')
print(t1)
print(t1[::-1])
print(t1[::2][::-2])


('s', 't', 'r', 'i', 'n', 'g')
('g', 'n', 'i', 'r', 't', 's')
('n', 's')


In [30]:
t3 = tuple([10,20,30,40,50,60])
print(60 in t3)
print('60' in t3)
print(int(10 in t3))
print(int(1 in t3))

True
False
1
0


In [36]:
s1 = input("Enter string:")
s2 = s1[::-1]
if s1 == s2:
    print("Palindrome")
else:
    print("Not Palindrome")

Enter string:yty
Palindrome


In [1]:
t = tuple(range(20,0,-5))
print(t)

(20, 15, 10, 5)


In [2]:
s = input("Enter a string: ")
print(list(s))

Enter a string: uyeiwr
['u', 'y', 'e', 'i', 'w', 'r']


In [6]:
print(type('1 2'.split()))
print(type([1, 3, 2].sort()))
print(type('abc'.upper()))
print(type(1 in [1,2]))

<class 'list'>
<class 'NoneType'>
<class 'str'>
<class 'bool'>
