Q1. create a numpy array of 5 zeros.  check datatype, itemsize and shape of above

In [2]:
import numpy as np
a = np.array([0,0,0,0,0])
print(a.dtype)
print(a.itemsize)
print(a.shape)

int32
4
(5,)


Q2. create a numpy array of ones of shape (5,4)

In [11]:
print(np.ones((5, 4) , dtype = np.int32) )

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Q3. create a matrix of shape 4,5 with numbers from 1-20

In [57]:
mat = np.arange(1, 21).reshape(4,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Q4. multiply all elements of above array by 10

In [51]:
print(mat * 10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


Q5. print odd elements from array

In [52]:
a = mat % 2 == 0
print("Odd elements are :")
print(mat[~a])

Odd elements are :
[ 1  3  5  7  9 11 13 15 17 19]


Q6. replace all even elements by their negative

In [60]:
a = mat % 2 == 0
print(-mat[a])

#alternative
print(np.where(mat%2== 0 , -mat, mat))


[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


Q7. create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

In [61]:
M1 = np.linspace(1 , 17, 16, dtype = np.int32).reshape(4, 4)
print(M1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 17]]


Q8. create a transpose of above matrix call it M2

In [62]:
M2 = M1.T
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 17]]


Q9. find sum of above matrix M3 = (M1 + M2)

In [63]:
M3 = M1 + M2
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 34]]


Q10. Find Transpose of M3, Call it MT1. Check if M3 == MT1

In [65]:
MT1 = M3.T
print(M3 == MT1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


Q11. find diffrence of M4 = (M1 - M2)

In [67]:
M4 = M1 - M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


Q12. Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

In [270]:
MT2 =M4.T
print(M4 ==MT2)
print()
print(M4 == -MT2)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


Q13. create a matrix (3x4) R1 of random numbers between 10-40

In [281]:
R1 = np.random.randint(10 , 40 , 12).reshape(3, 4)
print(R1)

[[10 23 34 17]
 [38 15 20 23]
 [26 33 36 29]]


Q14. find min and max column wise

In [283]:
print(np.min(R1, axis = 1))
print(np.max(R1, axis = 1))

[10 15 26]
[34 38 36]


Q15. replace the last column with sum of all the columns

In [285]:
R1 = np.random.randint(10 , 40, 12).reshape(3, 4)
print(R1)
print()
print("replacing the last column with sum of all the columns:")
M = R1[0:, 3]
R1[: , 3] = M.sum()
print(R1)

[[26 21 37 14]
 [22 28 38 36]
 [29 17 17 34]]

replacing the last column with sum of all the columns:
[[26 21 37 84]
 [22 28 38 84]
 [29 17 17 84]]


Q16. create a matrix (3x4) R1 of random numbers between 10-40

In [4]:
R1 = np.random.randint(10 , 40 ,15).reshape(3, 5)
print(R1)

[[22 35 21 15 20]
 [12 23 25 10 37]
 [33 29 25 21 27]]


Q17. replace all even elements with nan in R1

In [5]:
R1 = np.where (R1 % 2 == 0, np.nan, R1)
print(R1)


[[nan 35. 21. 15. nan]
 [nan 23. 25. nan 37.]
 [33. 29. 25. 21. 27.]]


Q18. count number of nan in R1

In [8]:
print(np.count_nonzero(np.isnan(R1)))

##alternative
print()
print(np.isnan(R1).sum())

4

4


Q19. Check the output of the code

In [341]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
